<?php
/**
 * Copyright (C) 2015, Some right reserved.
 * @author Kacper "Kadet" Donat <kadet1090@gmail.com>
 * @license http://creativecommons.org/licenses/by-sa/4.0/legalcode CC BY-SA
 *
 * Contact with author:
 * Xmpp: kadet@jid.pl
 * E-mail: kadet1090@gmail.com
 *
 * From Kadet with love.
 */

namespace Kadet\Mqtt;


use Kadet\Mqtt\Packet\Connect;
use Kadet\SocketLib\SocketClient;

class MqttClient extends SocketClient {
    public $username = null;
    public $password = null;
    public $will     = null;

    public $clientId = 'KadetMqttClient';

    public function __construct($address, $port, $transport = 'tcp', $timeout = 10)
    {
        parent::__construct($address, $port, $transport, $timeout); // TODO: Change the autogenerated stub

        $this->onConnect->add(function (MqttClient $client) {
            if(isset($this->logger)) $this->logger->info('Connected');

            $packet = new Connect('Nachujcitowiedziec');
            $packet->will = [
                'QoS' => 0x1,
                'topic' => 'test',
                'message' => 'test',
                'retain' => false
            ];
            $client->send($packet->__toString());
        });
    }


}